# TCL File Generated by Component Editor 13.0sp1
# Fri Sep 25 00:18:54 EEST 2015
# DO NOT MODIFY


# 
# matrix_mul_ip_s_int "matrix_mul_ip_s_int" v1.0
# Ovie 2015.09.25.00:18:54
# Matrix multiplier IP core (Integer)
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module matrix_mul_ip_s_int
# 
set_module_property DESCRIPTION "Matrix multiplier IP core (Integer)"
set_module_property NAME matrix_mul_ip_s_int
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "My Custom IP"
set_module_property AUTHOR Ovie
set_module_property DISPLAY_NAME matrix_mul_ip_s_int
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL AvalonInterfaceController
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file AvalonInterfaceController.vhd VHDL PATH ../HDL_Files/AvalonInterfaceController.vhd TOP_LEVEL_FILE
add_fileset_file BRAM18.vhd VHDL PATH ../HDL_Files/BRAM18.vhd
add_fileset_file BRAM_WRAPPER_V2.vhd VHDL PATH ../HDL_Files/BRAM_WRAPPER_V2.vhd
add_fileset_file CONTROL_UNIT_S_INT_G.vhd VHDL PATH ../HDL_Files/CONTROL_UNIT_S_INT_G.vhd
add_fileset_file DSP_INPUT_C.vhd VHDL PATH ../HDL_Files/DSP_INPUT_C.vhd
add_fileset_file GRAM.vhd VHDL PATH ../HDL_Files/GRAM.vhd
add_fileset_file GRAM_WRAPPER.vhd VHDL PATH ../HDL_Files/GRAM_WRAPPER.vhd
add_fileset_file MATRIX_MUL_IP_CORE_LIBRARY.vhd VHDL PATH ../HDL_Files/MATRIX_MUL_IP_CORE_LIBRARY.vhd
add_fileset_file MATRIX_MUL_IP_CORE_S_INT_G.vhd VHDL PATH ../HDL_Files/MATRIX_MUL_IP_CORE_S_INT_G.vhd
add_fileset_file Primitive_Adder_unsigned.vhd VHDL PATH ../HDL_Files/Primitive_Adder_unsigned.vhd
add_fileset_file Primitive_multiplier.vhd VHDL PATH ../HDL_Files/Primitive_multiplier.vhd
add_fileset_file STANDARD_RAM.vhd VHDL PATH ../HDL_Files/STANDARD_RAM.vhd
add_fileset_file txt_util.vhd VHDL PATH ../HDL_Files/txt_util.vhd


# 
# parameters
# 
add_parameter AVALON_DATA_WIDTH NATURAL 32
set_parameter_property AVALON_DATA_WIDTH DEFAULT_VALUE 32
set_parameter_property AVALON_DATA_WIDTH DISPLAY_NAME AVALON_DATA_WIDTH
set_parameter_property AVALON_DATA_WIDTH TYPE NATURAL
set_parameter_property AVALON_DATA_WIDTH UNITS None
set_parameter_property AVALON_DATA_WIDTH ALLOWED_RANGES 0:2147483647
set_parameter_property AVALON_DATA_WIDTH HDL_PARAMETER true
add_parameter NUM_OF_8_BIT_REGISTERS NATURAL 16
set_parameter_property NUM_OF_8_BIT_REGISTERS DEFAULT_VALUE 16
set_parameter_property NUM_OF_8_BIT_REGISTERS DISPLAY_NAME NUM_OF_8_BIT_REGISTERS
set_parameter_property NUM_OF_8_BIT_REGISTERS TYPE NATURAL
set_parameter_property NUM_OF_8_BIT_REGISTERS UNITS None
set_parameter_property NUM_OF_8_BIT_REGISTERS ALLOWED_RANGES 0:2147483647
set_parameter_property NUM_OF_8_BIT_REGISTERS HDL_PARAMETER true
add_parameter WRITE_DATA_CAPTURE_CYCLE NATURAL 1
set_parameter_property WRITE_DATA_CAPTURE_CYCLE DEFAULT_VALUE 1
set_parameter_property WRITE_DATA_CAPTURE_CYCLE DISPLAY_NAME WRITE_DATA_CAPTURE_CYCLE
set_parameter_property WRITE_DATA_CAPTURE_CYCLE TYPE NATURAL
set_parameter_property WRITE_DATA_CAPTURE_CYCLE UNITS None
set_parameter_property WRITE_DATA_CAPTURE_CYCLE ALLOWED_RANGES 0:2147483647
set_parameter_property WRITE_DATA_CAPTURE_CYCLE HDL_PARAMETER true
add_parameter COLUMN_TOTAL INTEGER 10
set_parameter_property COLUMN_TOTAL DEFAULT_VALUE 10
set_parameter_property COLUMN_TOTAL DISPLAY_NAME COLUMN_TOTAL
set_parameter_property COLUMN_TOTAL TYPE INTEGER
set_parameter_property COLUMN_TOTAL UNITS None
set_parameter_property COLUMN_TOTAL ALLOWED_RANGES -2147483648:2147483647
set_parameter_property COLUMN_TOTAL HDL_PARAMETER true
add_parameter OPCODE_WIDTH INTEGER 3
set_parameter_property OPCODE_WIDTH DEFAULT_VALUE 3
set_parameter_property OPCODE_WIDTH DISPLAY_NAME OPCODE_WIDTH
set_parameter_property OPCODE_WIDTH TYPE INTEGER
set_parameter_property OPCODE_WIDTH UNITS None
set_parameter_property OPCODE_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property OPCODE_WIDTH HDL_PARAMETER true
add_parameter ADDR_WIDTH INTEGER 5
set_parameter_property ADDR_WIDTH DEFAULT_VALUE 5
set_parameter_property ADDR_WIDTH DISPLAY_NAME ADDR_WIDTH
set_parameter_property ADDR_WIDTH TYPE INTEGER
set_parameter_property ADDR_WIDTH UNITS None
set_parameter_property ADDR_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ADDR_WIDTH HDL_PARAMETER true
add_parameter DATA_WIDTH INTEGER 18
set_parameter_property DATA_WIDTH DEFAULT_VALUE 18
set_parameter_property DATA_WIDTH DISPLAY_NAME DATA_WIDTH
set_parameter_property DATA_WIDTH TYPE INTEGER
set_parameter_property DATA_WIDTH UNITS None
set_parameter_property DATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DATA_WIDTH HDL_PARAMETER true
add_parameter DATA_WIDE_WIDTH INTEGER 48
set_parameter_property DATA_WIDE_WIDTH DEFAULT_VALUE 48
set_parameter_property DATA_WIDE_WIDTH DISPLAY_NAME DATA_WIDE_WIDTH
set_parameter_property DATA_WIDE_WIDTH TYPE INTEGER
set_parameter_property DATA_WIDE_WIDTH UNITS None
set_parameter_property DATA_WIDE_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DATA_WIDE_WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock_sink
set_interface_property avalon_slave_0 associatedReset reset_sink
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 waitrequest waitrequest Output 1
add_interface_port avalon_slave_0 read read Input 1
add_interface_port avalon_slave_0 write write Input 1
add_interface_port avalon_slave_0 readdata readdata Output avalon_data_width
add_interface_port avalon_slave_0 writedata writedata Input avalon_data_width
add_interface_port avalon_slave_0 address address Input 2
add_interface_port avalon_slave_0 chip_select chipselect Input 1
add_interface_port avalon_slave_0 byteenable byteenable Input avalon_data_width/8
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink clk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rst reset_n Input 1


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock ""
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end q_status export Output 8


# 
# connection point conduit_end_1
# 
add_interface conduit_end_1 conduit end
set_interface_property conduit_end_1 associatedClock ""
set_interface_property conduit_end_1 associatedReset ""
set_interface_property conduit_end_1 ENABLED true
set_interface_property conduit_end_1 EXPORT_OF ""
set_interface_property conduit_end_1 PORT_NAME_MAP ""
set_interface_property conduit_end_1 SVD_ADDRESS_GROUP ""

add_interface_port conduit_end_1 q_config export Output 8

